### ISSUE TITLE
How to install Platformus on existing ASP.NET website as addon?

### ISSUE THREAD

**Issue by smax239** [Platformus/Platformus#127]
ASP.NET + SQL Server

**Comment by KANekT** [comment]
example ? that you may install as addon current ?

**Comment by DmitrySikorsky** [comment]
Hi! It is very easy. Now we have problems with documentation,  but it will be fixed before release. So basically you just have to execute AddPlatformus and UsePlatformus methods inside your Startup class. Just take a look at Platformus-Sample project.

**Comment by DmitrySikorsky** [comment]
So, now there are a lot of docs. Also Platformus includes installer, so I close this issue for now. Feel free to reopen if have any additional questions.
