### ISSUE TITLE
Advisory - Platformus 1.0.0-alpha21

### ISSUE THREAD

**Issue by DanielBishtawi** [Platformus/Platformus#132]
Hello,

While testing we identified vulnerabilities in Platformus 1.0.0-alpha21. Can you please advise whom shall we contact to disclose the vulnerability details so it can be fixed and an email address?

Looking forward to hearing from you.

Regards,
Daniel Bishtawi

**Comment by DmitrySikorsky** [comment]
Hi! You can contact me (you can find my contacts on my website), thank you!

**Comment by DanielBishtawi** [comment]
Hi Dmitry,

Please provide an email address so that we can disclose the vulnerability details, http://www.platformus.net/ and http://sikorsky.pro/ do not have an email address which we can use.

Regards,
Daniel Bishtawi

**Comment by DmitrySikorsky** [comment]
Hi! Please add dmitry@ to my website domain, that will be my email.
