### ISSUE TITLE
Add Position/Level to Frontend Menu

### ISSUE THREAD

**Issue by atherosxd** [Platformus/Platformus#140]
Add Position/Level to Frondend Menu since Level on the MenuItemViewModel stays at 1 ignoring the position set on the backend

**Comment by DmitrySikorsky** [comment]
Hi! I think it is some kind of caching issue. Please try to restart the application to be sure it is about caching. (But I can't reproduce such behavior.)

**Comment by atherosxd** [comment]
Tried that. I'm using the nuget version btw. I have created my own menu view(cshtml) so that it will override the builtin one. But all menu items have Level set to 1 when debugging

**Comment by DmitrySikorsky** [comment]
Hm, level is not about position or sorting. It shows the nesting level of the menu item:

- 1
| - 2
|| - 3
- 1
| - 2
|| - 3

Items inside the menu (and inside the another items) are already sorted using the position,  so you don't  need it in the view.

**Comment by DmitrySikorsky** [comment]
I'm closing it for now. Feel free to reopen it any time if have any additional questions.
