### ISSUE TITLE
NullReferenceException on ObjectDirector ConstuctObject

### ISSUE THREAD

**Issue by atherosxd** [Platformus/Platformus#141]
**ConstructObject** will return a a **NullReferenceException** when passing a SerializeObject with a Member from a Parent. This can also be reproduced on the demo sample. 
e.g Class  Page member Content on Blog Post Page.

The NullReferenceException happens at line 67 where variable member is null.
since member Content cannot be found on Blog Post Page instead it can be found on the Parent.
can be fixed by using WithClassIdAndCodeInlcudingParent instead of WithClassIdAndCode

**Comment by DmitrySikorsky** [comment]
Thanks, that will be fixed.
