### ISSUE TITLE
Page Templates

### ISSUE THREAD

**Issue by feldrim** [Platformus/Platformus#147]
It's ok to me to hand code views but not for many users. It would be better to have a bunch of templates. 3 or 4 layouts for each sample blog, article, contacts, about etc page would be better. Then, letting the user code their own page by choosing Custom Layout would be more user friendly. And even after selecting a layout, in order to help users control their pages it is possible to add a customze button to redirect them to edit page.

**Comment by DmitrySikorsky** [comment]
Hi! Thank you for your comment.

I would say, that Platformus views edit feature is more for the developers, not for the end users. End users usually don't have enough skills to edit views, so you as developer should prepare all the templates for them.

But.

You can create your own Platformus installer (it's easy, I will create a demo for that) and provide your own usage scenarios and templates. This is cool feature for small IT companies which create simple (or even not so simple) websites for their customers.

**Comment by DmitrySikorsky** [comment]
Please, feel free to reopen this issue if you still have additional questions regarding it.
