### ISSUE TITLE
InvalidOperationException: Unable to resolve service for type 'ExtCore.Data.Abstractions.IStorageContext' while attempting to activate 'ExtCore.Data.EntityFramework.Storage'.

### ISSUE THREAD

**Issue by eravse** [Platformus/Platformus#151]
I created an application from scratch through the Nuget Packs as described in the document. If I run the app without any additional settings, I get the following error.

**I tried to reach you Address: / Backend**

**My reference page is: http://docs.platformus.net/en/latest/getting_started/use_as_nuget_packages.html**

InvalidOperationException: Unable to resolve service for type 'ExtCore.Data.Abstractions.IStorageContext' while attempting to activate 'ExtCore.Data.EntityFramework.Storage'.
Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteFactory.CreateArgumentCallSites(Type serviceType, Type implementationType, ISet<Type> callSiteChain, ParameterInfo[] parameters, bool throwIfCallSiteNotFound)
Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteFactory.CreateConstructorCallSite(Type serviceType, Type implementationType, ISet<Type> callSiteChain)
Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteFactory.TryCreateExact(ServiceDescriptor descriptor, Type serviceType, ISet<Type> callSiteChain)
Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteFactory.TryCreateExact(Type serviceType, ISet<Type> callSiteChain)
Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteFactory.CreateCallSite(Type serviceType, ISet<Type> callSiteChain)
Microsoft.Extensions.DependencyInjection.ServiceProvider.CreateServiceAccessor(Type serviceType, ServiceProvider serviceProvider)

**Comment by eravse** [comment]
The above error does not occur when downloading sample application from http://platformus.net/files/Platformus-Sample-1.0.0-beta2.zip. Just like it's happening for zero installation.

**Comment by DmitrySikorsky** [comment]
Hi! Could you share your project? It feels like concrete storage implementation packages are not added as dependencies (all ExtCore's package are not resolved). If you can't share the project, I will try to recreate this issue from scratch. Thank you!

UPD: also, you could take a look at this sample project: http://platformus.net/files/Platformus-Sample-1.0.0-beta2.zip and compare its dependencies with yours one.

**Comment by eravse** [comment]
Hi Dmitry yes i will be share. But just use nuget i am not install extra packages.

**Comment by eravse** [comment]
One example of transferring all the settings from the project to the new project was to reinstall ExCore to fix the problem.
