### ISSUE TITLE
Validation problem

### ISSUE THREAD

**Issue by eravse** [Platformus/Platformus#157]
I do not fully understand. However, when I go to the pages and add a class (Page type), all the page's fields come up. I just added a new field on the class that I added and did not get a warning like it can not be mandatory or null by clicking on the record button. Is this normal?

**Comment by DmitrySikorsky** [comment]
Hi! Sorry, it seems I missed your question or forgot to answer.

I'm not sure I understand it. When you  create a class, you can specify, whether some property is required or not. If you add another member to a class, which already contains the objects, this new property value will be null, even if it doesn't allows nulls. I think we could have something like default value, but now it is not implemented.

**Comment by DmitrySikorsky** [comment]
I will close this issue for now. Please feel free to reopen it any time if you have any additional questions.
