### ISSUE TITLE
Add basic user management in the UserManager class

### ISSUE THREAD

**Issue by DmitrySikorsky** [Platformus/Platformus#162]
Now this class only allows to validate, sign in and sign out users. We also need to have there methods for user registration, adding user to roles etc.

**Comment by weedkiller** [comment]
Hi, can you also plan to add tenant/group management too.. like multi-site,

**Comment by DmitrySikorsky** [comment]
Yes, you have created #54 some time ago :) We will have this feature, but I think in the version 2. Will see. Now I want to finish basic ecommerce module and release 1.0.0.

**Comment by weedkiller** [comment]
oops 😱  sorry, thanks 😄
