### ISSUE TITLE
'Startup' does not contain a definition for 'configurationRoot' ... 

### ISSUE THREAD

**Issue by adamongithub** [Platformus/Platformus#163]
I appears I've fallen at the first hurdle. The references to **this.extensionsPath** and **this.configurationRoot** cannot be resolved. I've triple checked my references to no avail. Can someone please let me know what I'm doing wrong?

```csharp
public void ConfigureServices(IServiceCollection services)
        {
            services.AddPlatformus(this.extensionsPath);  // compilation error
            services.Configure<StorageContextOptions>(options =>
            {
                options.ConnectionString = this.configurationRoot.GetConnectionString("Default");   // compilation error
            });
        }
```

Thanks

**Comment by stark11er** [comment]
Hello, same problem. Old docs dont help wth beta3.
Admin, please update docs for beta3. Thx!

**Comment by DmitrySikorsky** [comment]
Hi, yes, I will fix the docs. Now you can just pass 'null' instead of the extensionsPath.

Also, you download working Platformus sample: http://platformus.net/files/Platformus-Sample-1.0.0-beta3.zip

**Comment by DmitrySikorsky** [comment]
I will close this issue for now. Please feel free to reopen it any time if you have any additional questions.
