### ISSUE TITLE
when run web application,css and js can't load in html

### ISSUE THREAD

**Issue by weiwangda2014** [Platformus/Platformus#164]
![qq 20180208153123](https://user-images.githubusercontent.com/6489145/35960611-52a04cd0-0ce5-11e8-8c9d-f9d6a9c49716.png)
![qq 20180208153150](https://user-images.githubusercontent.com/6489145/35960612-52d7a05e-0ce5-11e8-9730-4697cbdbc551.png)

by the way,i use net core 2.0

**Comment by DmitrySikorsky** [comment]
Hi! Are you using Platformus from NuGet or from the source code?

You can try this 100% working (ready to  use) sample: http://platformus.net/files/Platformus-Sample-1.0.0-beta3.zip

**Comment by weiwangda2014** [comment]
i don't use  Platformus-Sample-1.0.0-beta3.zip, i just create new web project that it use core 2.0,and then css and js can't  work.

i have advise,you can create new web project to test.

**Comment by Xarkam** [comment]
Look your picture, you use Platformus
![image](https://user-images.githubusercontent.com/331816/35992822-abbd8ba4-0d0b-11e8-8037-30966143ff49.png)

Your method is not the correct for using Pjatformus.

What do you want to do ?

**Comment by weiwangda2014** [comment]
i just copy some code and config ,and than create new web project.

i don't understand what you mean?
@Xarkam

**Comment by DmitrySikorsky** [comment]
@weiwangda2014 but what about my questions?

**Comment by Xarkam** [comment]
@DmitrySikorsky , I do not understand what he wants to do.

A plugin?
Use the cms?

I do not understand why he creates a web project

**Comment by DmitrySikorsky** [comment]
I will close this issue for now. Please feel free to reopen it any time if you have any additional questions.
