### ISSUE TITLE
Starting on Azure

### ISSUE THREAD

**Issue by Jogai** [Platformus/Platformus#166]
I like that you have the getting started for a few scenarios. I think it would be nice to have a getting started for azure as well.

**Comment by DmitrySikorsky** [comment]
Hi! There is no problems to publish Platformus-based web application to Azure. It works with no problems. You can just follow one of the tutorials from the asp.net core docs website: https://docs.microsoft.com/en-us/aspnet/core/tutorials/publish-to-azure-webapp-using-vs

**Comment by DmitrySikorsky** [comment]
I will close this issue for now. Please feel free to reopen it any time if you have any additional questions.
