### ISSUE TITLE
Apply own design template

### ISSUE THREAD

**Issue by khanhtranchi** [Platformus/Platformus#177]
I have own a design template of my website, and I want to apply it to Platformus. Could you guide me how to do that ? I am going to create new empty website from visual studio and change the css, script of Platformus.

**Comment by DmitrySikorsky** [comment]
Hi! Could you explain what are you going to do? Because Platformus doesn't have any default frontend UI (CSS), you  have to write your own. So you can use ANY UI theme you want with no limitations.

Or you are talking about changing backend UI?
