### ISSUE TITLE
Custom Endpoints

### ISSUE THREAD

**Issue by ronikurnia1** [Platformus/Platformus#180]
Hi @DmitrySikorsky,  how to create custom endpoints class (inherits from EndpointBase) but can have IConfigurationManager as DI on its constructor?

Thanks

**Comment by DmitrySikorsky** [comment]
Hi! Yes, you can.

https://github.com/Platformus/Platformus/blob/master/src/Platformus.Domain.Frontend/Endpoints/DefaultEndpoint.cs#L34

Just use GetService extension method or use HttpRequest's RequestServices property directly.

**Comment by ronikurnia1** [comment]
Great, thank you @DmitrySikorsky !
