### ISSUE TITLE
Stored XSS - Edit Blog Post Page | Content Section

### ISSUE THREAD

**Issue by ismailtasdelen** [Platformus/Platformus#184]
Hello Security Team,

When I was a security researcher and student, I wanted to discover and report "Stored XSS" vulnerability.

![screenshot from 2018-07-17 19-46-34](https://user-images.githubusercontent.com/15425071/42832526-254c77e4-89fa-11e8-80fa-76b83e5b02aa.png)

Payload : "><img src=x onerror=alert('ismailtasdelen')>

Can the CVE reference number be provided ?

If you think about giving a prize. Can it be money or gift?

Thanks

**Comment by DmitrySikorsky** [comment]
Thank you, I will review this issue and answer.
