### ISSUE TITLE
Error runing as sources

### ISSUE THREAD

**Issue by jaullo** [Platformus/Platformus#187]
Hi peopele, 

I'm trying to run this project as sources as described here [RUN SOURCE](http://docs.platformus.net/en/latest/getting_started/use_as_sources.html)

Inside my appsettings i have configured sql server
```
"ConnectionStrings": {
    "Default": "Server=(local)\\technotel;Database=CoreERP;User Id=xx;Password=xxxx;"
  },
```

But after runnig the project, i get:

`System.InvalidOperationException: 'Cannot resolve scoped service 'ExtCore.Data.Abstractions.IStorage' from root provider`

This error appear in class: **UseLocalizationAction**

I'm sure my sql server is working without any problem.

Any help will be appreciated

Thanks

**Comment by jaullo** [comment]
It was resolved. Thanks

**Comment by vector-man** [comment]
Hey, do you care to share how you resolved this? Thanks! @jaullo

**Comment by DmitrySikorsky** [comment]
I think he just have added dependencies on the corresponding Platformus SqlServer packages.
