### ISSUE TITLE
View Not Found

### ISSUE THREAD

**Issue by jaullo** [Platformus/Platformus#188]
Hello People,

I'm trying to update the code to core 2.1 and ExtCore 3.3 
Code compiles without problem, but, when i try to move to /backend i get the following error

```
InvalidOperationException: The view 'SignIn' was not found. The following locations were searched:
/Areas/Backend/Views/Account/SignIn.en.cshtml
/Areas/Backend/Views/Account/SignIn.cshtml
/Areas/Backend/Views/Shared/SignIn.en.cshtml
/Areas/Backend/Views/Shared/SignIn.cshtml
/Views/Shared/SignIn.en.cshtml
/Views/Shared/SignIn.cshtml
/Pages/Shared/SignIn.en.cshtml
/Pages/Shared/SignIn.cshtml
```

Some one can help me?

Thanks

**Comment by DmitrySikorsky** [comment]
Please check that the views are correctly added as resources.

**Comment by jaullo** [comment]
Hi Dmitry, thank you for your answer. You pointed me in the right way, now views are resolved
