### ISSUE TITLE
BandleManager does not create bundles

### ISSUE THREAD

**Issue by py6jlb** [Platformus/Platformus#190]
Need add check exist output file, and if is not exist create it before write UglifyResult. Bundle not created, until output file not exist.

**Comment by DmitrySikorsky** [comment]
I think bundle manager doesn't create bundles when the output directory doesn't exist. Right? I don't think it is related to files...

**Comment by DmitrySikorsky** [comment]
So, we will automatically create folders before creating a bundle.
