### ISSUE TITLE
Old version ExtCore 3.2.0 in platformus

### ISSUE THREAD

**Issue by py6jlb** [Platformus/Platformus#192]
In nuget version platformus use ExtCore 3.2.0. I write simple module with data storage in sqlite db. I use last(3.3.0) version of package ExtCore.Data.Abstractions. When debug starting, i get error "A second operation started on this context before a previous operation completed...". For fix it, i change version ExtCore.Data.Abstractions package to previos(3.2.0).

**Comment by DmitrySikorsky** [comment]
I'm going to release the ExtCore 4.0.0-alpha1 soon, and I will move Platformus to it and release the new beta with ecommerce extension and some fixes ASAP.
