### ISSUE TITLE
When are you releasing first stable version.

### ISSUE THREAD

**Issue by nidheeshmca** [Platformus/Platformus#193]
When are you releasing first stable version or it will take time?

**Comment by DmitrySikorsky** [comment]
Now I'm going to release the new version of the ExtCore (Platformus is based on it). Then I will finish the first simplified version of the ECommerce extension. And after that I will provide number of fixes and changes we need in our team (we use Platformus for about 20-30 projects) and then release version 1.0.0. But I think it will take few month.
