### ISSUE TITLE
Blog cover image

### ISSUE THREAD

**Issue by TestPlato** [Platformus/Platformus#204]
Hi there,
after applying new version beta5, the things become bit better. I can now add a picture to the image uploader form, after which we have an option to choose the area.

However, when I click 'Done', a javascript error appears with code 500 Internal Server Error.
This is what it shows:
sourceImageUrl: /images/temp/cover.jpg
sourceX: 0
sourceY: 0
sourceWidth: 1024
sourceHeight: 256
destinationImageBaseUrl: /images/objects/
destinationWidth: 1024
destinationHeight: 256

Perhaps there is an error on the destinationImageBaseUrl, since we do not have a file name passed by the controller?

Please help.

**Comment by DmitrySikorsky** [comment]
The data-destination-base-url parameter is added to specify where to upload the images.
https://github.com/Platformus/Platformus/blob/master/src/Platformus.Barebone.Backend/Areas/Backend/Scripts/Behaviors/image_uploader_behavior.js#L24

**Comment by TestPlato** [comment]
OK, that's good.
However, what I can see now is that it WORK on the actual web server, but NOT on the local mashine, ie. using Visual Studio's IIS Express (localhost).
