### ISSUE TITLE
Contacts - submit button error

### ISSUE THREAD

**Issue by TestPlato** [Platformus/Platformus#205]
Hi there,
after applying the new version5, we suddnely got a new error:
- modul: Contacts
- error: SqlException: Invalid column name 'SubmitButtonTitle'.

In the previous version all was OK.

**Comment by DmitrySikorsky** [comment]
Please, take a look at SQL scheme: https://github.com/Platformus/Platformus/blob/master/sqlite_scheme.sql#L324

It has been changed a bit to allow to specify submit button label.

**Comment by TestPlato** [comment]
OK, good.

Problem solved.
