### ISSUE TITLE
Post pages - tags

### ISSUE THREAD

**Issue by TestPlato** [Platformus/Platformus#206]
Hi there,
it seems the tags on the post pages are not working.

1. there is no functionality to add/edit tags,
2. I managed to change the names on the existing tags (Tag1, ...Tag5) in the Localizations table and they display correctly during the editing of the post.

However, when we simply show the post on the web page, it still display #Tag1 #Tag3.

I cannot see from where those names are comming. I am using SQL Server database.

**Comment by DmitrySikorsky** [comment]
Hi,

Tags are regular Platformus objects. There is the Tag class you can see in the Administration section of the backend. Also, BlogPost class has the Tags member with the corresponding relation.
