### ISSUE TITLE
Blog pagination

### ISSUE THREAD

**Issue by TestPlato** [Platformus/Platformus#207]
Hi there,

it looks like the pagination on the blog list doesn't work.

I have 10 blog posts and I specified on Edit Data Sources 'Enable paging' with Default “Take” URL parameter value to be 3.

The blog list correctly display the last 3 only post.

However, there is no pagination, so I am unable to select any previous post outside the first 3.

How can we display pagination on the BlogPage?

**Comment by DmitrySikorsky** [comment]
Hi,

Standard data sources supports pagination from URL parameters (use ?skip=0&take=1, or you can specify custom parameter names). But you need to implement your own pager.
