### ISSUE TITLE
ASP.NET Core Identity Integration? 

### ISSUE THREAD

**Issue by vector-man** [Platformus/Platformus#208]
Hello,

Just discovered your CMS. I want an option open for using another Identity provider in admin and user management. Is there any support for the new ASP.NET Core Identity libraries? https://docs.microsoft.com/en-us/aspnet/core/security/authentication/identity?view=aspnetcore-2.2&tabs=visual-studio

**Comment by DmitrySikorsky** [comment]
Hi,

Not yet. I decided that Identity is too complicated and its default User objects contains a lot of functionallity I don't need, so I decided to go with the own simple implementation. It uses the built in ASP.NET Core auth methods, so it is fully integrated in the standard flow.

**Comment by vector-man** [comment]
Thanks for the answer! Will definitely use the CMS anyway and try to get Identity in later. Was trying to get this integrated https://github.com/aws/aws-aspnet-cognito-identity-provider

Any idea on if/when you might have support available?

**Comment by DmitrySikorsky** [comment]
I think it should support OAuth, Saml etc. But I think these are tasks for the future.

**Comment by prince272** [comment]
I've rewritten the Asp Core Identity for Mvc. Feel free to take a look at https://github.com/prince272/AspCoreIdentityMvc

Simply change the url for the area 'Identity' to 'IdentityMvc' and you'll be automatically directed to the Mvc version for Identity.
