### ISSUE TITLE
Files from the Views, Styles, Scripts folder in the admin panel (Ubuntu 18.04) are not displayed.

### ISSUE THREAD

**Issue by sultanlive** [Platformus/Platformus#211]
Files from the Views, Styles, Scripts folder in the admin panel (Ubuntu 18.04) are not displayed. Due to the wrong way.
File Platformus.Designers/PathManager.cs (line 140 Combine method)

Example:
method Combine returned - "home/username/project/Views"
true returned - "**/**home/username/project/Views"

**Comment by DmitrySikorsky** [comment]
@sultanlive thanks, will look at it.

**Comment by DmitrySikorsky** [comment]
Views, Styles, Scripts, as well as Extension Manager, won't be supported anymore because of the new understanding of the project as the CMS for developers, not for end users.
