### ISSUE TITLE
Set Culture programatically

### ISSUE THREAD

**Issue by senadburak** [Platformus/Platformus#212]
Hi there,

is it possible to set one of existing cultures programatically from controller?

Rgds. Senad

**Comment by DmitrySikorsky** [comment]
Hi @senadburak. Yes, you can change the culture inside the controller, but culture is set every request using the standard culture providers: https://github.com/Platformus/Platformus/blob/master/src/Platformus.Globalization.Frontend/Actions/UseLocalizationAction.cs#L57

Setting it inside the controller is not the correct way. I would suggest rather to replace RouteValueRequestCultureProvider with your own one.

**Comment by senadburak** [comment]
Dmitry,
thank you for a quick response. However, I was unable to implement what I want.

To better understand the problem, I will try to explain it with more detailes. In short, I have my own Controller and my own Views which I use in addition to the standard Platformus Views (PostPage, BlogPage etc.)

Wen I use standard Platformus views, everything is working fine in relation to the chosen Culture. All menus, views and content will be shown in that Culture (ie. English, German etc.)

The problem is however with my own Views (which are not related to the standard Platformus views). In such cases, I want to set my view in accordance to what Culture is selected. That is, if the Culture is "de", I want to programatically keep all menus, pages  etc to show German content.

Unfortunatelly, I was unable to do it. My views always set the default Culture (English) for all menus, pages etc, although the chosen Culture was German.

So, any idea how to deal with this problem?

Rgds. Senad
