### ISSUE TITLE
[Admin panel] Objects->Regular pages has correct page count, but the list is empty (cannot edit/delete)

### ISSUE THREAD

**Issue by rexTexTau** [Platformus/Platformus#214]
Steps to reproduce:

1) Build the Platformus from source code
2) Use the ecommerce-demo sample as a site
3) Get in use a MSSQL database, running the initial SQL script from the ecommerce-demo, and altering the connection string in config.
4) Go to Backend -> Objects -> Regular Pages

See: https://ibb.co/cJcnLWD

**Comment by DmitrySikorsky** [comment]
I think we can ignore it for now, because this will be changed in 2.0.0. I will verify it.

**Comment by DmitrySikorsky** [comment]
There are no serialized objects now, so it is not possible anymore.
