### ISSUE TITLE
[Admin panel] Objects->Create regular page missing URL texbox (cannot set URL, as well as create a new page)

### ISSUE THREAD

**Issue by rexTexTau** [Platformus/Platformus#215]
Steps to reproduce:
1) Build the Platformus from source code
2) Use the ecommerce-demo sample as a site
3) Get in use a MSSQL database, running the initial SQL script from the ecommerce-demo, and altering the connection string in config.
4) Go to Backend -> Objects -> Regular Pages -> Create regular page

See: https://ibb.co/0DR1gv9

"URL" label is present, but the textbox is completely missing - so, cannot set it in any way, as well as save the newly created page.

**Comment by DmitrySikorsky** [comment]
I will review if it is still actual for the 2.0.0.
