### ISSUE TITLE
.NET 5.0

### ISSUE THREAD

**Issue by senadburak** [Platformus/Platformus#219]
Any plan to adopt the solution to the just released .NET 5.0?

SB

**Comment by DmitrySikorsky** [comment]
Yes. I'm currenlty on it. I'm going to merge extensions in few ones, update everything to be async, improve perfomance etc. First beta should be available in about 2-3 weeks.

**Comment by senadburak** [comment]
OK, thanks Dmitry.

Looking forward to see it done.

Rgds. Senad

**Comment by DmitrySikorsky** [comment]
Done.
