### ISSUE TITLE
[Page editing] Datetime field not saved properly on creation, only during edition of created page

### ISSUE THREAD

**Issue by rexTexTau** [Platformus/Platformus#220]
Steps to reproduce:
1) Go to "Create object" page, that has at least one datetime field.
2) Select arbitrary date
3) Press save
4) Go to the newly created page to ensure that the date you've selected is not set - the date of page creation is displayed (and stored) instead.

P.S. If you open this page for editing, change the date and press save - voila, all set!

**Comment by DmitrySikorsky** [comment]
Hi @rexTexTau! Thank you, I will review if this issue is still actual on Platformus 2.0.0-alpha1 which is going to be released in few days.
