### ISSUE TITLE
[Admin panel: menu] Ability to create HTML menu items

### ISSUE THREAD

**Issue by rexTexTau** [Platformus/Platformus#223]
At the moment, there is no ability to add html code to the menu items via admin panel's menu page. 
Technically, you could - but the html stored in the menu item value is escaped, and raw html code becomes visible in frontend.
There are various real-world scenarios, where menu items are to include different icons before each item (not ONE icon - this is quite simply could be done using css pre, but VARIOUS icons), or even contain the icon only (for example, envelope instead of "Mail us").

This seems more like than enhancement, rather than bug, but it will be very useful if admin panel provided the capability to render unescaped HTML menu item values.

P.S. https://developer.mozilla.org/en-US/docs/Web/CSS/:nth-child , combined with pre of course will do the trick, but the overall way of doing that seems hacky and unclean.

**Comment by DmitrySikorsky** [comment]
You can just use your own partial views to render menu in some your way. As I mentioned in another issue created by you.

Just copy the _Menu or _MenuItem partial view in your main web app and modify them.
