### ISSUE TITLE
[Admin panel] TinyMCE 4 annoying message while editing HTML fields

### ISSUE THREAD

**Issue by rexTexTau** [Platformus/Platformus#225]
"Your access to TinyMCE will expire on 25 Februrary 2021. Please either contact your administrator or upgrade your account using the instructions available here." - this message is shown while editing HTML object fields.

Presumably, upgrade from TinyMCE 4 to TinyMCE 5 needed.

**Comment by DmitrySikorsky** [comment]
It will be (it is actually) fixed in 2.0.0.
