### ISSUE TITLE
2.0 error

### ISSUE THREAD

**Issue by senadburak** [Platformus/Platformus#228]
Hi there,
did you noticed that we have a problem with the new version 2.0 for NET Core 5.0?

At startup, we got an error saying:
"InvalidOperationException: Scheme already exists: BackendCookies"

Even the sample blog web site, downloaded from github, have the same problem.

Hope this will be fixed soon.

**Comment by DmitrySikorsky** [comment]
Hi, 2.0.0 works, but the samples are old, they need to be fixed. They will be fixed soon. There are a lot of changes, so you can't just update the project to start using 2.0.0 from 1.1.0.

You can look at this one: https://github.com/Platformus/Platformus-Sample-Mobile-App-Admin-Panel

It is the only one updated so far.

**Comment by senadburak** [comment]
Thank you Dmitry.

Regarding the Mobil App, could you please explain how to run it.

The thing is, when I launch it (withouth any nodification) from Visual Studio IIS Express, I get the error:

This localhost page can’t be found
No webpage was found for the web address: http://localhost:1234/
HTTP ERROR 404

What to do please?

**Comment by DmitrySikorsky** [comment]
Yes, you get 404 because API doesn't contain any UI. Just navigate to /en/v1/categories or /en/v1/products

You will be able to use sorting and paging.

Samples will be updated soon, so everything will be clear. I think, in 2-5 days.

**Comment by DmitrySikorsky** [comment]
This one is updated: https://github.com/Platformus/Platformus-Sample-Personal-Website

Please, look at it. SQL scripts are updated too.

**Comment by senadburak** [comment]
Sorry, but it is not working (404)

SB

**Comment by DmitrySikorsky** [comment]
Added readme information: https://github.com/Platformus/Platformus-Sample-Mobile-App-Admin-Panel
