### ISSUE TITLE
Remove explicit HTTP protocol from google font CSS url

### ISSUE THREAD

**Issue by DmitrySikorsky** [Platformus/Platformus#26]
https://github.com/Platformus/Platformus/blob/master/src/Platformus.Barebone/BackendMetadata.cs#L18

**Comment by KANekT** [comment]
https://github.com/Platformus/Platformus/blob/85686cc8ee87c425b610b4cc02aaa8e74d3e5f04/src/Platformus.Content.Backend/Areas/Backend/Views/ImageUploader/Index.cshtml#L12

fix it :)

**Comment by DmitrySikorsky** [comment]
You are right, it needs to be fixed too!
