### ISSUE TITLE
Add Compression Middleware

### ISSUE THREAD

**Issue by KANekT** [Platformus/Platformus#47]
Add Response Compression Middleware in ASP.NET Core
Example:
http://dotnetthoughts.net/using-response-compression-middleware-in-aspnet-core/
https://www.janaks.com.np/enabling-gzip-compression-asp-net-core-1-1-application/
https://ievangelist.github.io/blog/asp-net-core-optimization/

**Comment by KANekT** [comment]
https://metanit.com/sharp/aspnet5/14.3.php in Russian

**Comment by KANekT** [comment]
Example module in Orhard
https://github.com/OrchardCMS/Orchard2/commit/6c79d503ab9d6739b9d8224ec853573d93ef0d76

**Comment by DmitrySikorsky** [comment]
It can be done just using ExtCore features, so it has nothing to do with Platformus.
