### ISSUE TITLE
Platformus.Navigation not support Second menu

### ISSUE THREAD

**Issue by KANekT** [Platformus/Platformus#5]
Then I create second menu in

http://demo.platformus.net/backend/menus 

after save - redirect in main page && menu not created

**Comment by DmitrySikorsky** [comment]
Now it is possible to add the second menu, but I've found new bug: it is not possible to remove menu or menu item when using SQLite. It is because of SQLite doesn't support WHILE loop and variables, so SQL must be rewritten.
