### ISSUE TITLE
Fix images resizing and cropping

### ISSUE THREAD

**Issue by DmitrySikorsky** [Platformus/Platformus#51]
Our image uploader doesn't really resize or crop images now, we need to fix that.

**Comment by KANekT** [comment]
Example library for resize: https://github.com/JimBobSquarePants/ImageSharp

**Comment by KANekT** [comment]
http://magick.codeplex.com/documentation?referringTitle=Home

Use in Facebook

**Comment by DmitrySikorsky** [comment]
Will fix when ImageSharp is available in NuGet (instead of MyGet).

**Comment by DmitrySikorsky** [comment]
Good article to read. I think I will consider using CoreCompat:
https://blogs.msdn.microsoft.com/dotnet/2017/01/19/net-core-image-processing/

**Comment by DmitrySikorsky** [comment]
Will use CoreCompat.System.Drawing for that.
