### ISSUE TITLE
Get rid of Session in the project

### ISSUE THREAD

**Issue by DmitrySikorsky** [Platformus/Platformus#62]
To be able to scale the application (for example, in Azure) it needs to be stateless. So we shouldn't use session. Now we use it for only one simple thing: to copy form field values between requests during the validation. I think we may use cookies for that or something else. Need to think.

**Comment by frabe1579** [comment]
Maybe ITempDataProvider can be the solution. It can uses cookies, ad is perfect for inter-request data exchange.
See [https://docs.microsoft.com/en-us/aspnet/core/fundamentals/app-state](https://docs.microsoft.com/en-us/aspnet/core/fundamentals/app-state), section TempData.

**Comment by DmitrySikorsky** [comment]
Very interesting, thank you! I think it may work.
