### ISSUE TITLE
use sql server

### ISSUE THREAD

**Issue by mghalgar** [Platformus/Platformus#69]
i can't use sql server , because i can't add-migration

**Comment by KANekT** [comment]
Migration not support now.

**Comment by mghalgar** [comment]
how to use sql server without migration?

**Comment by DmitrySikorsky** [comment]
Hi! Please take a look at config.json.template. There is the connection string for a SQL Server database. Just use it and it will work. I use the SQL Server with no problems.

**Comment by mghalgar** [comment]
SqlException: Cannot open database "platformus" requested by the login. The login failed.
Login failed for user 'DESKTOP-D4913GI\Mohammad'.

**Comment by DmitrySikorsky** [comment]
It is not related to the Platformus. You have wrong connection string. Try to connect to the DB from the VS Server Explorer. It can generate a connection string for you.

**Comment by mghalgar** [comment]
i create a module , but database new table don't created , how to migrate ?

**Comment by DmitrySikorsky** [comment]
Migrations are not working in ExtCore, I don't know for now how to fix them in the modular application. Just create the table manually. If you have any ideas how to make migrations work in the ExtCore I will be happy to add this in the new releases.

**Comment by mghalgar** [comment]
can i add ExtCore.Data.EntityFramework.SqlServer as project to my solution and Add-Migration from package manager console ??
@DmitrySikorsky

**Comment by DmitrySikorsky** [comment]
I really don't know for now. I think I have to learn and discover more about that and then I will be able to answer.
