### ISSUE TITLE
bundle not working

### ISSUE THREAD

**Issue by mghalgar** [Platformus/Platformus#70]
hi , some time in frontend or backend , bundle not working and stylesheet not loaded

**Comment by DmitrySikorsky** [comment]
Hi! What do you mean that bundle not working? You change the styles in the backend and they are not compiled to the output css automatically?

**Comment by mghalgar** [comment]
I don't chabge, current style not loaded

**Comment by DmitrySikorsky** [comment]
If you have downloaded the sources of the sample (not ready to use sample) there are no css file there. I would suggest to download ready to use sample. Other option is to go to the backend, open the styles file and then click Save. The minified bundle will be created and you will have your css file. The same for the js.
