### ISSUE TITLE
Install the project

### ISSUE THREAD

**Issue by vahidsaberi** [Platformus/Platformus#77]
1-How to install the project with install project?
2-How to create scripts of DB from models or make a database with new update models?

**Comment by DmitrySikorsky** [comment]
1. Hi! Installer will be done closer to beta version. Now use ready to use sample. New alpha with a lot of changes will be released in few days BTW.
2. Sample contains the db scripts and there is the SQLite db in the ready to use sample.

**Comment by vahidsaberi** [comment]
tnx👍🏻👍🏻

**Comment by DmitrySikorsky** [comment]
So, I'm going to fix this task soon. I think we will have wizard-like installation. And user will be able to:

1. Select storage type (PostgreSQL, SQLite or SQL Server for now).
2. Specify connection string to the storage.
3. Select template for the future web application (empty, blog, company website, shop and so on).
4. Specify admin username and password.
