### ISSUE TITLE
viewComponent as taghelper

### ISSUE THREAD

**Issue by mghalgar** [Platformus/Platformus#78]
viewComponent as taghelper not working

**Comment by DmitrySikorsky** [comment]
Thank you! I will look at it.

**Comment by DmitrySikorsky** [comment]
So, I have tested and it actually works. To make it work you should register tag helper for example as:

`@addTagHelper "*, Platformus.Globalization.Frontend"`

Then you will be able to use CulturesViewComponent like this:

`<vc:cultures></vc:cultures>`
